"""Build ``analysis/fmv/02_fmv_1_agent2_review.md`` — a case-by-case review
of Agent 2's (non-canonical) structural-axis resolutions.

Mirrors v0.2's `analysis/aristotelian/v0_2_agent2_review.md`. For each of the 7
structural-axis dual-judge disagreement cases (labelled Case 1-7) it
shows: both structural judges' verdicts + reasoning, and how Agent 2
(`gemini-3.1-pro-preview`, non-canonical resolver) ruled — its
verdict, which judge it sided with, its recomputed rule count, and its
reasoning verbatim.

Agent 2 is a side analysis — NOT the prereg disagree resolution; the
human audit (`02_fmv_1_structural_audit_worksheet.md`) is canonical.
This review documents Agent 2's behaviour for the eventual
Agent-2-vs-human comparison.

Usage: ``uv run python scripts/build_02_fmv_1_agent2_review.py``
"""

from __future__ import annotations

import glob
import json
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "results"
FRAMEWORK_ID = "02_fmv"
OUTPUT = REPO / "analysis" / "fmv" / "02_fmv_1_agent2_review.md"
MODELS = ("claude-opus-4-7", "gpt-5.5-2026-04-23", "gemini-3.1-pro-preview")


def _structural(model: str) -> dict[tuple[int, str], dict[str, Any]]:
    out: dict[tuple[int, str], dict[str, Any]] = {}
    for fp in sorted(glob.glob(str(RESULTS / model / FRAMEWORK_ID / "structural" / "*.json"))):
        d = json.loads(Path(fp).read_text())
        name = Path(d["trial_path"]).name
        if name.startswith("trial_"):
            out[(int(name.split("_")[1]), d["judge_family"])] = d.get("parsed_verdict") or {}
    return out


def _agent2(model: str) -> dict[int, dict[str, Any]]:
    """{trial_index: full Agent 2 record}."""
    out: dict[int, dict[str, Any]] = {}
    for fp in sorted(
        glob.glob(str(RESULTS / model / FRAMEWORK_ID / "structural_resolved" / "*.json"))
    ):
        d = json.loads(Path(fp).read_text())
        d["_file"] = Path(fp).name
        out[d["trial_index"]] = d
    return out


def _verdict(parsed: dict[str, Any]) -> str | None:
    raw = parsed.get("verdict")
    if not isinstance(raw, str):
        return None
    up = raw.strip().upper()
    return up if up in {"PASS", "FAIL"} else None


def _judge_lines(label: str, parsed: dict[str, Any]) -> list[str]:
    fc = ", ".join(parsed.get("failed_criteria") or []) or "(none)"
    return [
        f"**{label} — `{_verdict(parsed)}`** (Stage 1 rule count "
        f"`{parsed.get('stage1_rule_count', '?')}`, failed: {fc})",
        "",
        f"> {(parsed.get('reasoning') or '').strip()}",
        "",
    ]


def main() -> None:
    cases: list[tuple[str, int]] = []
    structural: dict[str, dict[tuple[int, str], dict[str, Any]]] = {}
    agent2: dict[str, dict[int, dict[str, Any]]] = {}
    for model in MODELS:
        sv = _structural(model)
        structural[model] = sv
        agent2[model] = _agent2(model)
        for trial in range(5):
            a = sv.get((trial, "anthropic"))
            b = sv.get((trial, "openai"))
            if a is None or b is None:
                continue
            va, vb = _verdict(a), _verdict(b)
            if va and vb and va != vb:
                cases.append((model, trial))

    # Headline tallies.
    a2_verdicts = []
    sided = {"judge_a": 0, "judge_b": 0, "neither": 0}
    for model, trial in cases:
        rec = agent2[model].get(trial, {})
        pv = rec.get("parsed_verdict") or {}
        a2_verdicts.append(_verdict(pv))
        sw = pv.get("agreed_with")
        if sw in sided:
            sided[sw] += 1
    n_fail = sum(1 for v in a2_verdicts if v == "FAIL")
    n_pass = sum(1 for v in a2_verdicts if v == "PASS")

    lines: list[str] = []
    lines.append("# 02_fmv.1 Agent 2 — structural-axis side-resolution review")
    lines.append("")
    lines.append("> Generated by `scripts/build_02_fmv_1_agent2_review.py`. Case-by-case")
    lines.append("> review of the 7 structural-axis dual-judge disagreement cases:")
    lines.append(
        "> - **Claude / OpenAI structural judges** — the two `02_fmv.1` structural judges."
    )
    lines.append("> - **Agent 2** — `gemini-3.1-pro-preview`, a NON-CANONICAL resolver: it")
    lines.append(">   reads both judges' verdicts + the frozen structural criteria and")
    lines.append(">   returns PASS/FAIL. Agent 2 does **not** feed P1 / P2 — the human")
    lines.append(">   audit (`02_fmv_1_structural_audit_worksheet.md`) is canonical.")
    lines.append("> Source JSONs: `results/<model>/02_fmv/structural{,_resolved}/*.json`.")
    lines.append("")
    lines.append("## Headline")
    lines.append("")
    lines.append(
        f"**Structural-axis IRR: {len(cases)} of 15 trials = "
        f"{len(cases) / 15:.2%}.** Above v0.2 Aristotelian's 40% — see "
        f"`02_fmv_1_findings.md` (P1 REFUTED)."
    )
    lines.append("")
    lines.append(
        f"**Agent 2 across the {len(cases)} disagree cases:** FAIL = {n_fail}, PASS = {n_pass}."
    )
    lines.append("")
    lines.append(
        f"**Agent 2 sided with:** Claude structural judge on {sided['judge_a']}/"
        f"{len(cases)}; OpenAI structural judge on {sided['judge_b']}/{len(cases)}; "
        f"neither on {sided['neither']}/{len(cases)}."
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    for k, (model, trial) in enumerate(cases, start=1):
        a = structural[model][(trial, "anthropic")]
        b = structural[model][(trial, "openai")]
        rec = agent2[model].get(trial, {})
        pv = rec.get("parsed_verdict") or {}

        lines.append(f"## Case {k} — `{model}` trial {trial}")
        lines.append("")
        lines += _judge_lines("Claude structural judge", a)
        lines += _judge_lines("OpenAI structural judge", b)

        fc = ", ".join(pv.get("failed_criteria") or []) or "(none)"
        lines.append(
            f"### Agent 2 resolution — **`{_verdict(pv)}`** "
            f"(agreed_with: `{pv.get('agreed_with', '?')}`)"
        )
        lines.append("")
        lines.append(f"- Agent 2's own Stage 1 rule count: `{pv.get('stage1_rule_count', '?')}`")
        lines.append(f"- failed_criteria: `{fc}`")
        lines.append(f"- reasoning: {(pv.get('reasoning') or '').strip()}")
        lines.append("")
        lines.append(
            f"_(verdict JSON: `results/{model}/02_fmv/structural_resolved/{rec.get('_file', '?')}`)_"
        )
        lines.append("")
        lines.append("---")
        lines.append("")

    text = "\n".join(line.rstrip() for line in lines)
    OUTPUT.write_text(text.rstrip() + "\n")
    print(f"Wrote {OUTPUT.relative_to(REPO)} — {len(cases)} cases (Case 1-{len(cases)}).")


if __name__ == "__main__":
    main()
