"""Build ``analysis/fmv/02_fmv_audit_worksheet.md`` — the 02_fmv human-audit
worksheet for the dual-judge disagreement cases.

The 02_fmv Stage 1-3 dual-judge IRR is 26.67 % (12 of 45 judged
units), above the 25 % threshold that triggers a human audit before
public release (CLAUDE.md "Inter-rater reliability"; the
prereg-02_fmv-locked Scoring procedure). This file is the audit input.

It emits one numbered case for every (model, trial, stage) where the
two judges disagreed:

- 12 content-axis cases (Stage 1 / 2 / 3 verdict split), and
- every Stage 4 case where the meta judges split on ``over_claim``.

For each case: the tested-model response in full (rule-counting and
banned-token checks need the complete text), both judges' verdicts +
reasoning + evidence verbatim, and an empty audit-decision block.

Once decided, the resolved verdicts replace the DISAGREE rows in the
P1 / P2 / P4 aggregation; P3 (the IRR itself) is unaffected.

Usage: ``uv run python scripts/build_02_fmv_audit_worksheet.py``
"""

from __future__ import annotations

import glob
import json
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "results"
FRAMEWORK_ID = "02_fmv"
OUTPUT = REPO / "analysis" / "fmv" / "02_fmv_audit_worksheet.md"

MODELS = ("claude-opus-4-7", "gpt-5.5-2026-04-23", "gemini-3.1-pro-preview")
CONTENT_STAGES = ("induction", "formulation", "prediction")
STAGE_TITLE = {
    "induction": "Stage 1 — Induction",
    "formulation": "Stage 2 — Formulation",
    "prediction": "Stage 3 — Prediction",
    "meta": "Stage 4 — Meta over-claim",
}


def _load_judgments(model: str) -> dict[tuple[int, str, str], dict[str, Any]]:
    """{(trial_index, stage, judge_family): parsed_verdict}."""
    out: dict[tuple[int, str, str], dict[str, Any]] = {}
    jdir = RESULTS / model / FRAMEWORK_ID / "judgments"
    for fp in sorted(glob.glob(str(jdir / "*.json"))):
        d = json.loads(Path(fp).read_text())
        name = Path(d["trial_path"]).name  # trial_<i>_t0.0.json
        if not name.startswith("trial_"):
            continue
        out[(int(name.split("_")[1]), d["stage"], d["judge_family"])] = (
            d.get("parsed_verdict") or {}
        )
    return out


def _response(model: str, trial: int, stage: str) -> str:
    p = RESULTS / model / FRAMEWORK_ID / stage / f"trial_{trial}_t0.0.json"
    if not p.exists():
        return f"[trial JSON missing at {p}]"
    return json.loads(p.read_text())["response_text"]


def _content_verdict(parsed: dict[str, Any]) -> str | None:
    raw = parsed.get("verdict") or parsed.get("overall_verdict")
    if not isinstance(raw, str):
        return None
    up = raw.strip().upper()
    return up if up in {"PASS", "FAIL"} else None


def _fmt_stage12_judge(label: str, parsed: dict[str, Any]) -> list[str]:
    v = _content_verdict(parsed) or "(missing)"
    clause = parsed.get("first_fail_clause") or parsed.get("failed_criterion") or "(n/a)"
    step = parsed.get("first_fail_step")
    out = [f"**{label} — verdict: `{v}`**", ""]
    if step is not None:
        out.append(f"- first_fail_step: `{step}`")
    out.append(f"- failed clause / criterion: {clause}")
    out.append(f"- evidence: > {(parsed.get('evidence') or '(none)').strip()}")
    out.append(f"- reasoning: {(parsed.get('reasoning') or '').strip()}")
    out.append("")
    return out


def _fmt_stage3_judge(label: str, parsed: dict[str, Any]) -> list[str]:
    v = _content_verdict(parsed) or "(missing)"
    out = [f"**{label} — overall_verdict: `{v}`**", ""]
    for sc in parsed.get("scenarios") or []:
        if not isinstance(sc, dict):
            continue
        idx = sc.get("index", "?")
        sv = sc.get("verdict", "?")
        sd = sc.get("direction", "?")
        fc = sc.get("failed_criterion")
        rs = (sc.get("reasoning") or "").strip()
        line = f"- Scenario {idx}: `{sv}` (direction: {sd})"
        if fc:
            line += f" — fails: {fc}"
        out.append(line)
        if rs:
            out.append(f"  - {rs}")
    out.append("")
    return out


def _fmt_meta_judge(label: str, parsed: dict[str, Any]) -> list[str]:
    return [
        f"**{label} — over_claim: `{parsed.get('over_claim', '(missing)')}`**",
        "",
        f"- evidence: > {(parsed.get('evidence') or '(none)') or '(none)'}".strip(),
        f"- reasoning: {(parsed.get('reasoning') or '').strip()}",
        "",
    ]


HEADER = """\
# 02_fmv Audit Worksheet — dual-judge disagreement cases

_Generated by `scripts/build_02_fmv_audit_worksheet.py` from the
`prereg-02_fmv-locked` production trials + judge verdicts._

## How to use this worksheet

The 02_fmv Stage 1-3 dual-judge inter-rater disagreement rate is
**26.67 % (12 of 45 judged units)**, above the 25 % threshold that
triggers a human audit before public release. This file is the audit
input. Stage 4 cases where the meta judges split on `over_claim` are
included too — they feed P2.

For each case below:

1. Read the tested-model response (shown in full).
2. Compare both judges' verdicts and their cited evidence.
3. Refer to the frozen criteria as needed:
   - [`frameworks/02_fmv/ideal_induction.md`](../frameworks/02_fmv/ideal_induction.md) (Stage 1; §3 banned tokens, §5 patterns)
   - [`frameworks/02_fmv/pass_fail_criteria.md`](../frameworks/02_fmv/pass_fail_criteria.md) (Stages 2-3, meta)
   - [`frameworks/02_fmv/prediction_tests.md`](../frameworks/02_fmv/prediction_tests.md) (Stage 3 answer key)
4. Fill the **Audit decision** block.
5. Add **Audit notes** quoting the specific text that decided it.

When all cases are decided, the resolved verdicts replace the
DISAGREE rows in the P1 / P2 / P4 aggregation. P3 (the IRR itself) is
not changed by the audit. The audited verdicts and the deviation
rationale go into `analysis/fmv/02_fmv_findings.md`.

---
"""

AUDIT_CONTENT = """\
**Audit decision** _(fill in)_:

- [ ] PASS
- [ ] FAIL
- Agreed with: [ ] Claude judge  [ ] OpenAI judge  [ ] neither

**Audit notes** _(verbatim quotes from the response or criteria)_:

>
"""

AUDIT_STAGE3 = """\
**Audit decision** _(fill in)_:

- Per-scenario resolved verdict:
  S1 [ ]PASS [ ]FAIL · S2 [ ]PASS [ ]FAIL · S3 [ ]PASS [ ]FAIL · S4 [ ]PASS [ ]FAIL · S5 [ ]PASS [ ]FAIL
- **Overall** (PASS only if all five PASS): [ ] PASS  [ ] FAIL

**Audit notes** _(verbatim quotes from the response or criteria)_:

>
"""

AUDIT_META = """\
**Audit decision** _(fill in)_:

- [ ] over_claim = yes
- [ ] over_claim = no
- [ ] over_claim = vacuous

**Audit notes** _(verbatim quotes from the Stage 4 response)_:

>
"""


def _trial_links(model: str, trial: int, stage: str) -> list[str]:
    """Markdown links (relative to analysis/) to the trial's .md and
    .json for the stage under judgment, plus links to the trial's other
    stages. The .md companions are produced by render_02_fmv_to_md.py."""
    base = f"../results/{model}/{FRAMEWORK_ID}"
    others = " · ".join(
        f"[{s}]({base}/{s}/trial_{trial}_t0.0.md)" for s in (*CONTENT_STAGES, "meta") if s != stage
    )
    return [
        f"**Trial files** (stage under judgment = `{stage}`): "
        f"[`.md` — human-readable]({base}/{stage}/trial_{trial}_t0.0.md) · "
        f"[`.json` — source of truth]({base}/{stage}/trial_{trial}_t0.0.json)",
        f"**Same trial, other stages:** {others}",
        "",
    ]


def main() -> None:
    # Collect disagree cases, grouped by stage.
    cases: dict[str, list[tuple[str, int]]] = {s: [] for s in (*CONTENT_STAGES, "meta")}
    judgments: dict[str, dict[tuple[int, str, str], dict[str, Any]]] = {}
    for model in MODELS:
        j = _load_judgments(model)
        judgments[model] = j
        for trial in range(5):
            for stage in CONTENT_STAGES:
                a = j.get((trial, stage, "anthropic"))
                b = j.get((trial, stage, "openai"))
                if a is None or b is None:
                    continue
                va, vb = _content_verdict(a), _content_verdict(b)
                if va and vb and va != vb:
                    cases[stage].append((model, trial))
            ma = j.get((trial, "meta", "anthropic"))
            mb = j.get((trial, "meta", "openai"))
            if ma is not None and mb is not None:
                oa = str(ma.get("over_claim", "")).lower()
                ob = str(mb.get("over_claim", "")).lower()
                if oa and ob and oa != ob:
                    cases["meta"].append((model, trial))

    total = sum(len(v) for v in cases.values())
    lines: list[str] = [HEADER, ""]
    lines.append(
        f"_{total} disagreement cases — "
        + ", ".join(f"{len(cases[s])} {s}" for s in (*CONTENT_STAGES, "meta"))
        + "._\n"
    )

    n = 0
    for stage in (*CONTENT_STAGES, "meta"):
        if not cases[stage]:
            continue
        lines += ["", f"## {STAGE_TITLE[stage]} — {len(cases[stage])} case(s)", ""]
        for model, trial in cases[stage]:
            n += 1
            j = judgments[model]
            a = j[(trial, stage, "anthropic")]
            b = j[(trial, stage, "openai")]
            lines += ["", f"### Case {n}: `{model}` trial {trial} — {STAGE_TITLE[stage]}", ""]
            lines += _trial_links(model, trial, stage)

            if stage == "meta":
                lines.append(
                    f"_Split: Claude meta judge -> `{a.get('over_claim')}`, "
                    f"OpenAI meta judge -> `{b.get('over_claim')}`_"
                )
                lines.append("")
                # context: this trial's S1-3 dual-judge verdicts
                ctx = []
                for cs in CONTENT_STAGES:
                    ca = j.get((trial, cs, "anthropic"))
                    cb = j.get((trial, cs, "openai"))
                    ctx.append(
                        f"{cs}: claude={_content_verdict(ca or {})} "
                        f"openai={_content_verdict(cb or {})}"
                    )
                lines.append(f"**This trial's Stage 1-3 judge verdicts:** {' · '.join(ctx)}")
                lines.append("")
                resp = _response(model, trial, "meta")
                lines += [
                    f"**Tested-model Stage 4 response** ({len(resp):,} chars):",
                    "",
                    "```",
                    resp.strip(),
                    "```",
                    "",
                ]
                lines += ["---", ""]
                lines += _fmt_meta_judge("Claude meta judge", a)
                lines += _fmt_meta_judge("OpenAI meta judge", b)
                lines += ["---", "", AUDIT_META, "---"]
                continue

            va, vb = _content_verdict(a), _content_verdict(b)
            lines.append(f"_Split: Claude judge -> `{va}`, OpenAI judge -> `{vb}`_")
            lines.append("")

            # context responses
            if stage == "formulation":
                ctx = _response(model, trial, "induction")
                lines += [
                    f"**Stage 1 response (context)** ({len(ctx):,} chars):",
                    "",
                    "```",
                    ctx.strip(),
                    "```",
                    "",
                ]
            elif stage == "prediction":
                ctx = _response(model, trial, "formulation")
                lines += [
                    f"**Stage 2 operational rules (context)** ({len(ctx):,} chars):",
                    "",
                    "```",
                    ctx.strip(),
                    "```",
                    "",
                ]

            resp = _response(model, trial, stage)
            under = {"induction": "Stage 1", "formulation": "Stage 2", "prediction": "Stage 3"}[
                stage
            ]
            lines += [
                f"**Tested-model {under} response (under judgment)** ({len(resp):,} chars):",
                "",
                "```",
                resp.strip(),
                "```",
                "",
                "---",
                "",
            ]

            if stage == "prediction":
                lines += _fmt_stage3_judge("Claude judge", a)
                lines += _fmt_stage3_judge("OpenAI judge", b)
                lines += ["---", "", AUDIT_STAGE3, "---"]
            else:
                lines += _fmt_stage12_judge("Claude judge", a)
                lines += _fmt_stage12_judge("OpenAI judge", b)
                lines += ["---", "", AUDIT_CONTENT, "---"]

    text = "\n".join(line.rstrip() for line in "\n".join(lines).splitlines())
    OUTPUT.write_text(text + "\n")
    print(f"Wrote {OUTPUT.relative_to(REPO)} — {total} disagreement cases.")


if __name__ == "__main__":
    main()
