"""Build ``analysis/decay/03_decay_agents_review.md`` — the non-canonical
Agent 1 + Agent 2 verdicts in one file, paired with each judge's
verdict and the case meta-data, for **after-audit** reference.

The human audit in ``analysis/decay/03_decay_audit_worksheet.md`` is the
canonical resolution per the prereg. This file is published as a
side analysis: a record of how the two LLM resolvers
(``gemini-3.1-pro-preview``) classified each pending case, against
which the human audit can be compared as a calibration metric
(V1-style, parallel to the 02_fmv and v0.3 Agent reports).

Usage: ``uv run python scripts/build_03_decay_agents_review.py``
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "results"
FRAMEWORK_ID = "03_decay"
OUTPUT = REPO / "analysis" / "decay" / "03_decay_agents_review.md"
MODELS = ("claude-opus-4-7", "gpt-5.5-2026-04-23", "gemini-3.1-pro-preview")


def _short(s: Any, maxlen: int = 280) -> str:
    if not isinstance(s, str):
        return "(none)"
    s = s.strip().replace("\n", " ")
    return s if len(s) <= maxlen else s[: maxlen - 3] + "..."


def main() -> None:
    # Agent 1 verdicts
    a1_rows: list[dict[str, Any]] = []
    for model in MODELS:
        d = RESULTS / model / FRAMEWORK_ID / "content_resolved"
        if not d.exists():
            continue
        for fp in sorted(d.glob("*.json")):
            rec = json.loads(fp.read_text())
            pv = rec.get("parsed_verdict") or {}
            a1_rows.append(
                {
                    "model": model,
                    "trial": rec["trial_index"],
                    "stage": rec["stage"],
                    "ja": rec["judge_a_verdict"],
                    "jb": rec["judge_b_verdict"],
                    "verdict": pv.get("verdict", "PARSE_ERROR"),
                    "agreed_with": pv.get("agreed_with", "-"),
                    "failed_clause": pv.get("failed_clause") or "-",
                    "evidence": _short(pv.get("evidence_quote")),
                    "reasoning": _short(pv.get("reasoning"), 500),
                }
            )

    # Agent 2 verdicts
    a2_rows: list[dict[str, Any]] = []
    for model in MODELS:
        d = RESULTS / model / FRAMEWORK_ID / "scenario_resolved"
        if not d.exists():
            continue
        for fp in sorted(d.glob("*.json")):
            rec = json.loads(fp.read_text())
            pv = rec.get("parsed_verdict") or {}
            a2_rows.append(
                {
                    "model": model,
                    "trial": rec["trial_index"],
                    "scenario": rec["scenario_index"],
                    "reason": rec["case_reason"],
                    "ja_v": rec["judge_a_verdict"],
                    "ja_d": rec["judge_a_direction"],
                    "jb_v": rec["judge_b_verdict"],
                    "jb_d": rec["judge_b_direction"],
                    "verdict": pv.get("verdict", "PARSE_ERROR"),
                    "direction": pv.get("direction", "-"),
                    "agreed_with": pv.get("agreed_with", "-"),
                    "evidence": _short(pv.get("evidence_quote")),
                    "reasoning": _short(pv.get("reasoning"), 500),
                }
            )

    lines: list[str] = [
        "# 03_decay Agents Review — non-canonical Agent 1 + Agent 2 verdicts",
        "",
        "_Generated by `scripts/build_03_decay_agents_review.py`._",
        "",
        "**Status:** non-canonical. Published as a side analysis to compare "
        "against the human audit in "
        "[`03_decay_audit_worksheet.md`](./03_decay_audit_worksheet.md), "
        "in the V1-style calibration tradition used since 02_fmv. The "
        "canonical disagree-resolver per "
        "[`predictions/03_decay_prereg.md`](../predictions/03_decay_prereg.md) "
        "§1.4 is the human audit.",
        "",
        "Both agents are `gemini-3.1-pro-preview`, run from "
        "`scripts/run_agent1_03_decay.py` and `scripts/run_agent2_03_decay.py` "
        "against the locked 03_decay criteria.",
        "",
        "## Headlines",
        "",
        f"- Agent 1 (content-axis verdict resolver): **{len(a1_rows)} cases**. "
        "Distribution: "
        + ", ".join(
            f"{k}={sum(1 for r in a1_rows if r['agreed_with'] == k)}"
            for k in ("judge_a", "judge_b", "neither", "-")
        ),
        "",
        f"- Agent 2 (Stage 3 per-scenario resolver): **{len(a2_rows)} cases**. "
        "Bucket distribution: "
        + f"decay-correct={sum(1 for r in a2_rows if r['verdict'] == 'PASS')}, "
        f"ratio-leaked={sum(1 for r in a2_rows if r['verdict'] == 'FAIL' and r['direction'] == 'correct')}, "
        f"direction-wrong={sum(1 for r in a2_rows if r['verdict'] == 'FAIL' and r['direction'] == 'wrong')}",
        "",
        "Agent 1 strongly agrees with the Claude judge "
        f"({sum(1 for r in a1_rows if r['agreed_with'] == 'judge_a')}/{len(a1_rows)}) "
        "— directly reflecting Gap 4 (OpenAI judge §3-token fabrication on "
        "the Decay World), where most OpenAI FAIL verdicts cited evidence "
        "that the mechanical evidence_check could not locate in the tested "
        "response.",
        "",
        "Combined with the original consensus units, the **post-agent P3 "
        "distribution** across 60 quantitative predictions is "
        f"decay-correct {13 + sum(1 for r in a2_rows if r['verdict'] == 'PASS')}, "
        f"ratio-leaked {15 + sum(1 for r in a2_rows if r['verdict'] == 'FAIL' and r['direction'] == 'correct')}, "
        f"direction-wrong {0 + sum(1 for r in a2_rows if r['verdict'] == 'FAIL' and r['direction'] == 'wrong')}. "
        "(The human audit will confirm or revise these.)",
        "",
        "---",
        "",
        "# Part A — Agent 1 content-axis verdicts",
        "",
        "| # | Tested model | Trial | Stage | Claude | OpenAI | Agent 1 | Agreed with | Failed clause |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    for n, r in enumerate(a1_rows, start=1):
        lines.append(
            f"| A1-{n} | `{r['model']}` | {r['trial']} | {r['stage']} | "
            f"{r['ja']} | {r['jb']} | **{r['verdict']}** | {r['agreed_with']} | "
            f"`{r['failed_clause']}` |"
        )

    lines += ["", "## Agent 1 per-case detail", ""]
    for n, r in enumerate(a1_rows, start=1):
        lines += [
            f"### A1-{n}: `{r['model']}` t{r['trial']} {r['stage']}",
            "",
            f"- Claude: `{r['ja']}` · OpenAI: `{r['jb']}` · "
            f"**Agent 1: `{r['verdict']}` (with `{r['agreed_with']}`)**",
            f"- Failed clause: `{r['failed_clause']}`",
            f"- Evidence quote: > {r['evidence']}",
            f"- Reasoning: {r['reasoning']}",
            "",
        ]

    lines += [
        "---",
        "",
        "# Part B — Agent 2 Stage 3 per-scenario verdicts",
        "",
        "| # | Tested model | Trial | Scenario | Reason | Claude | OpenAI | Agent 2 | Bucket |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for n, r in enumerate(a2_rows, start=1):
        if r["verdict"] == "PASS":
            bucket = "decay-correct"
        elif r["verdict"] == "FAIL" and r["direction"] == "correct":
            bucket = "ratio-leaked"
        elif r["verdict"] == "FAIL" and r["direction"] == "wrong":
            bucket = "direction-wrong"
        else:
            bucket = "(other)"
        lines.append(
            f"| A2-{n} | `{r['model']}` | {r['trial']} | s{r['scenario']} | "
            f"{r['reason'][:40]} | {r['ja_v']}/{r['ja_d']} | "
            f"{r['jb_v']}/{r['jb_d']} | "
            f"**{r['verdict']}/{r['direction']}** | {bucket} |"
        )

    lines += ["", "## Agent 2 per-case detail", ""]
    for n, r in enumerate(a2_rows, start=1):
        lines += [
            f"### A2-{n}: `{r['model']}` t{r['trial']} scenario {r['scenario']}",
            "",
            f"- Reason: `{r['reason']}`",
            f"- Claude: `{r['ja_v']}`/`{r['ja_d']}` · "
            f"OpenAI: `{r['jb_v']}`/`{r['jb_d']}` · "
            f"**Agent 2: `{r['verdict']}`/`{r['direction']}` "
            f"(with `{r['agreed_with']}`)**",
            f"- Evidence quote: > {r['evidence']}",
            f"- Reasoning: {r['reasoning']}",
            "",
        ]

    text = "\n".join(line.rstrip() for line in lines)
    OUTPUT.write_text(text.rstrip() + "\n")
    print(
        f"Wrote {OUTPUT.relative_to(REPO)} — "
        f"{len(a1_rows)} Agent 1 + {len(a2_rows)} Agent 2 entries."
    )


if __name__ == "__main__":
    main()
