"""Build ``analysis/fmv/02_fmv_1_structural_audit_worksheet.md`` — the
02_fmv.1 human-audit worksheet for the structural-axis disagreements.

The 02_fmv.1 structural-axis dual-judge IRR is 46.67 % (7 of 15
trials), above the 25 % threshold that triggers a human audit before
release (the `prereg-02_fmv.1-locked` Scoring procedure). This file is
the audit input.

One numbered case per (model, trial) where the two structural judges
split. For each case: the full Stage 1 response (the rule set under
judgment) and the full Stage 2 response (context), both structural
judges' verdicts + rule counts + failed criteria + evidence +
reasoning verbatim, and an empty per-criterion audit block.

Agent 2's resolver verdicts are deliberately **not** shown here — the
human audit is meant to be independent, so the Agent-2-vs-human
comparison stays meaningful.

Usage: ``uv run python scripts/build_02_fmv_1_structural_worksheet.py``
"""

from __future__ import annotations

import glob
import json
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "results"
FRAMEWORK_ID = "02_fmv"
OUTPUT = REPO / "analysis" / "fmv" / "02_fmv_1_structural_audit_worksheet.md"
MODELS = ("claude-opus-4-7", "gpt-5.5-2026-04-23", "gemini-3.1-pro-preview")


def _structural(model: str) -> dict[tuple[int, str], dict[str, Any]]:
    out: dict[tuple[int, str], dict[str, Any]] = {}
    for fp in sorted(glob.glob(str(RESULTS / model / FRAMEWORK_ID / "structural" / "*.json"))):
        d = json.loads(Path(fp).read_text())
        name = Path(d["trial_path"]).name
        if name.startswith("trial_"):
            out[(int(name.split("_")[1]), d["judge_family"])] = d.get("parsed_verdict") or {}
    return out


def _response(model: str, trial: int, stage: str) -> str:
    p = RESULTS / model / FRAMEWORK_ID / stage / f"trial_{trial}_t0.0.json"
    if not p.exists():
        return f"[trial JSON missing at {p}]"
    return json.loads(p.read_text())["response_text"]


def _verdict(parsed: dict[str, Any]) -> str | None:
    raw = parsed.get("verdict")
    if not isinstance(raw, str):
        return None
    up = raw.strip().upper()
    return up if up in {"PASS", "FAIL"} else None


def _fmt_judge(label: str, parsed: dict[str, Any]) -> list[str]:
    fc = ", ".join(parsed.get("failed_criteria") or []) or "(none)"
    out = [
        f"**{label} — verdict: `{_verdict(parsed)}`**",
        "",
        f"- stage1_rule_count: `{parsed.get('stage1_rule_count', '?')}`",
        f"- failed_criteria: `{fc}`",
        "- evidence:",
    ]
    ev = parsed.get("evidence") or []
    if not ev:
        out.append("  - (none)")
    for e in ev:
        if not isinstance(e, dict):
            continue
        crit = e.get("criterion", "?")
        quote = (e.get("quote") or "").strip().replace("\n", " ")
        expl = (e.get("explanation") or "").strip()
        out.append(f"  - **{crit}** — > {quote}")
        if expl:
            out.append(f"    - _{expl}_")
    out.append(f"- reasoning: {(parsed.get('reasoning') or '').strip()}")
    out.append("")
    return out


def _trial_links(model: str, trial: int) -> list[str]:
    base = f"../results/{model}/{FRAMEWORK_ID}"
    return [
        f"**Trial files:** Stage 1 [`.md`]({base}/induction/trial_{trial}_t0.0.md) "
        f"· [`.json`]({base}/induction/trial_{trial}_t0.0.json) — "
        f"Stage 2 [`.md`]({base}/formulation/trial_{trial}_t0.0.md) "
        f"· [`.json`]({base}/formulation/trial_{trial}_t0.0.json)",
        "",
    ]


HEADER = """\
# 02_fmv.1 Structural Audit Worksheet — dual-judge disagreement cases

_Generated by `scripts/build_02_fmv_1_structural_worksheet.py` from the
`prereg-02_fmv.1-locked` structural verdicts._

## How to use this worksheet

The 02_fmv.1 structural-axis dual-judge inter-rater disagreement rate
is **46.67 % (7 of 15 trials)**, above the 25 % threshold that
triggers a human audit before release. This file is the audit input.

For each case below:

1. Read the **Stage 1** response — that is the rule set under
   judgment. Stage 2 is shown as context; it is never counted (the
   v0.2 double-count fix).
2. Apply the 6-step procedure in
   [`frameworks/02_fmv/structural_criteria.md`](../frameworks/02_fmv/structural_criteria.md)
   — N9 parsimony, N10 independence, N11 traceability, N12 hierarchy.
3. Compare the two judges' verdicts, rule counts, and cited evidence.
4. Fill the **Audit decision** block: your own Stage 1 rule count, a
   PASS/FAIL for each of N9-N12, an overall verdict, and which judge
   you agreed with.
5. Add **Audit notes** quoting the text that decided it.

The resolved verdicts replace the DISAGREE rows in the composite table
and finalise P2. P1 (the structural IRR itself) is not changed by the
audit. Agent 2's resolver verdicts are kept out of this worksheet so
your audit stays independent.

---
"""

AUDIT = """\
**Audit decision** _(fill in)_:

- Your Stage 1 rule count: `____`
- N9 — Parsimony:    [ ] PASS  [ ] FAIL
- N10 — Independence: [ ] PASS  [ ] FAIL
- N11 — Traceability: [ ] PASS  [ ] FAIL
- N12 — Hierarchy:    [ ] PASS  [ ] FAIL
- **Overall structural verdict:** [ ] PASS  [ ] FAIL
- Agreed with: [ ] Claude judge  [ ] OpenAI judge  [ ] neither

**Audit notes** _(verbatim quotes from the Stage 1 response or criteria)_:

>
"""


def main() -> None:
    cases: list[tuple[str, int]] = []
    verdicts: dict[str, dict[tuple[int, str], dict[str, Any]]] = {}
    for model in MODELS:
        sv = _structural(model)
        verdicts[model] = sv
        for trial in range(5):
            a = sv.get((trial, "anthropic"))
            b = sv.get((trial, "openai"))
            if a is None or b is None:
                continue
            va, vb = _verdict(a), _verdict(b)
            if va and vb and va != vb:
                cases.append((model, trial))

    lines: list[str] = [HEADER, ""]
    lines.append(f"_{len(cases)} structural disagreement cases._\n")

    for n, (model, trial) in enumerate(cases, start=1):
        a = verdicts[model][(trial, "anthropic")]
        b = verdicts[model][(trial, "openai")]
        s1 = _response(model, trial, "induction")
        s2 = _response(model, trial, "formulation")
        lines += [
            "",
            f"## Case {n}: `{model}` trial {trial} — structural axis (N9-N12)",
            "",
            f"_Split: Claude structural judge -> `{_verdict(a)}`, "
            f"OpenAI structural judge -> `{_verdict(b)}`_",
            "",
        ]
        lines += _trial_links(model, trial)
        lines += [
            f"### Stage 1 — induction (rule set under judgment, {len(s1):,} chars)",
            "",
            "```",
            s1.strip(),
            "```",
            "",
            f"### Stage 2 — formulation (context only, never counted, {len(s2):,} chars)",
            "",
            "```",
            s2.strip(),
            "```",
            "",
            "---",
            "",
        ]
        lines += _fmt_judge("Claude structural judge", a)
        lines += _fmt_judge("OpenAI structural judge", b)
        lines += ["---", "", AUDIT, "---"]

    text = "\n".join(line.rstrip() for line in "\n".join(lines).splitlines())
    OUTPUT.write_text(text + "\n")
    print(f"Wrote {OUTPUT.relative_to(REPO)} — {len(cases)} structural disagreement cases.")


if __name__ == "__main__":
    main()
